writer.go

Let the client determine if it should cache or not unless we are
publishing a live stream.

Move the writing of the no cache header to inside playlist type event.

---

writer.go

From my initial testing I ran into a issue where the URI was missing quotes, in other places the library adds quotes for you.

Adding quotes to URI to make the external API nicer.

---

writer.go

Safe way to know how many items are in the media playlist. New getter retrieves p.count

Effectively exporting mediapl count

---

writer.go
writer_test.go

Fixed a bug where the Audio group was not being set using the Audio variable on the VariantParams, it was instead using the video group name.
The change to the Count() method was done automatically by go fmt, which my IDE runs on every save.

Fixed Audio group name being incorrectly set to the Video group name

---

writer.go

Currently if the same group is referenced multiple times, it will appear multiple times in the HLS output which is incorrect.
This change keeps track of this and will only write out the same group (currently by composing a composite key of type, group Id, Name * Language) once.

Fix alt duplicates

---

writer.go

The HLS specification allows for a SUBTITLES attribute to be set on EXT-X-STREAM-INF entries:
https://tools.ietf.org/html/draft-pantos-http-live-streaming-16#section-4.3.4.2
This pull-request causes the SUBTITLES attribute to be set if the variant has the Subtitles field set on the struct.

Produce the SUBTITLES attribute for EXT-X-STREAM-INF entries

---

writer.go

Сейчас при вызове ```playlist.SetKey("AES-128", KeyUrl, "", "", "")``` у плейлиста будет версия 5, хотя должна быть 3.
В стандарте есть требование к версии медиа плейлиста для шифрованного HLS:
```
A Media Playlist MUST indicate a EXT-X-VERSION of 5 or higher if it contains:
- The KEYFORMAT and KEYFORMATVERSIONS attributes of the EXT-X-KEY tag.
```
Т.е. 5-я версия должна быть *только* если присутствуют атрибуты KEYFORMAT и KEYFORMATVERSIONS.

Fix playlist version in SetKey method

---

writer.go
writer_test.go

As defined in the HLS  V5 spec:
>   A Playlist MUST indicate protocol version 5 or higher if it contains:
o  The KEYFORMAT and KEYFORMATVERSIONS attributes of the EXT-X-KEY
tag.
However any HLS version > 2 is compatible with EXT-X-KEY tags containing only METHOD, URI and IV attributes.
It looks like this behaviour was fixed for the `SetKey` function, but not `SetDefaultKey`. I added the fix to `SetDefaultKey` and a couple of tests around it.
I also changed the behaviour of `SetDefaultKey` to return an `error` value to make it more resemble `SetKey`

Fixed unnecessary playlist version change in SetDefaultKey

---

writer.go

Getting KEYFORMAT and KEYFORMATVERSIONS to propagate through into the manifest generation

Adding support for SAMPLE-AES manifests

---

writer.go
writer_test.go

Previously media playlists were assumed to have no query parameters when
encoding a master manifest with Args. This commit first checks if the
URI contains existing params (checks for "?") and if so, appends new
Args with a leading "&", else it will add "?".

Append Args if playlist already has query params

---

writer.go

Previously, when a segment has different encryption parameters than the
default playlist, the Encode() function uses the segment's parameters for
all parameters but `Keyformat` and `Keyformatversions`.
This change uses the segment's `Keyformat` and `Keyformatversions` when the
segments are encoded, allowing these parameters to change per segment and
not requiring a playlist to have a key set.
An `Encode()` at the end of the `TestSetKeyForMediaPlaylist` test would show a nil pointer exception, as the playlist did not have a key initialised, but the Encode() function would try and access it anyway.

Use segment Keyformat and Keyformatversions on MediaPlaylist.Encode()

---

reader_test.go
writer.go
writer_test.go

Fixed [Why replace seqNo 0 to 1? · Issue #37 · grafov/m3u8](https://github.com/grafov/m3u8/issues/37)

Remove normalize SeqNo. Allow starting 0

---

writer.go
writer_test.go

HLS draft RFC (draft-pantos-http-live-streaming-18) section 4.3.2.4
states that the use of KEYFORMAT REQUIRES playlist version 5 or
greater, and also state the use of KEYFORMATVERSIONS requires playlist
version 5 or greater.
Section 7 then states version 5 is required if "The KEYFORMAT and
KEYFORMATVERSIONS attributes of the EXT-X-KEY tag.",
Currently the version number is incremented only if both options are set.
As some devices set one to its default value and omit the other, the
playlist should increment the version number if either of these options
are set.

Increment pls version when either KEYFORMAT or KEYFORMATVERSIONS is set

---

writer.go
writer_test.go

Expands upon #40 to support encoding the SCTE segments into a playlist.
Such that the following:
```
package main
import (
"fmt"
"github.com/grafov/m3u8"
)
func main() {
p, _ := m3u8.NewMediaPlaylist(1, 1)
_ = p.Append("test01.ts", 5.0, "")
_ = p.SetSCTE("CueData", "ID", 3.141)
fmt.Print(p.String())
}
```
Outputs:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:5
#EXT-X-SCTE:CUE="CueData",ID="ID",TIME=3.141
#EXTINF:5.000,
test01.ts
```

Support EXT-X-SCTE when encoding playlists

---

writer.go
writer_test.go

Adds new method to media playlist AppendSegment(), providing the ability to append a MediaSegment to the playlist, similar to Append().
Normally a user would append a segment and use various Set methods to change the previous segment's properties, however, it would become tedious when copying segments from one playlist to another.

Add media playlist AppendSegment(*MediaSegment) method

---

doc.go

p.Decode expects a Bytes object, p.DecodeFrom accepts the reader

Fixed documentation

---

writer.go
writer_test.go

Currently version is controlled via private version functions and
set via the Set* methods when required. This is the ideal method for
most applications, as the version is managed by the library
This change provides the user the ability to check the version as
well as overwrite it, as during some live streams the version number
may have been incremented via the Set methods, but once those
segments have been removed the version number will change during
playback. This isn't ideal as the player may encounter version changes
during playback to versions it doesn't support. This provides
implementors the ability to announce up front what the version number
will be.

Expose master and media playlist version setter and getter methods

---

reader.go
reader_test.go
writer.go
writer_test.go

Alternative implementation of the improvements by @hori-ryota - all credits for actual changes is theirs. 
This PR cherry picks the biggest impact but lowest risk and maintains ABI compatibility.
This is only an example PR, and will need verification, approval and rebasing before merging.
This branch:
Before:
```
BenchmarkDecodeMasterPlaylist-4   100000             22425 ns/op           12195 B/op         77 allocs/op
BenchmarkDecodeMediaPlaylist-4        50          23947209 ns/op        12279896 B/op     160059 allocs/op
BenchmarkEncodeMasterPlaylist-4  1000000              1023 ns/op              40 B/op         11 allocs/op
BenchmarkEncodeMediaPlaylist-4       100          12931950 ns/op         1748991 B/op      81607 allocs/op
```
After:
```
BenchmarkDecodeMasterPlaylist-4   100000 …
```

Hori improvements - Alternative approach

---

reader.go
reader_test.go
writer.go
writer_test.go

There are three related commits here all addressing issues.
0f55de01b9a5bf2be3f843e9279e54de59281a7a fixes #53 and finishes #22, this exposes two new methods for a media playlist, `SetWinSet()` and `WinSize()` which sets and gets the winsize respectively.
78a4147c7f5d2cd5f91b29cb712634394d444c35 fixes #5, when decoding a playlist using the `Decode()` or `DecodeFrom()` functions (not the equivalent methods on a Master/Media Playlist), the decode function would create a new media playlist with a winsize of 8 and capacity of 1024. If the playlist was >1024 segments, the remaining segments would be dropped.
This auto extends the playlist in this case (not when using the media playlist decode methods) but doubling its size each time. In no other cases are playlists extendable. …

Auto extend media playlist, expose winsize, set winsize 0 on VoD

---

example/example.go

Use `path.Join` to create a file path.
we can avoid these common errors.
- path/tofile
- path/to//file
Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grafov/m3u8/73)

Use path.Join in example

---

.travis.yml

I met this error in travis-ci.
```bash
$ $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
flag needs an argument: -repotoken
...
The command "$GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN" exited with 2.
```
`$COVERALLS_TOKEN` is not necessary.
c.f. [Docs](https://github.com/mattn/goveralls#travis-ci)
> For a public github repository, it is not necessary to define your repository key (COVERALLS_TOKEN).
In other ways, add `=` like this.
maybe, it works.
- before:	`-repotoken $COVERALLS_TOKEN`
- after:	`-repotoken=$COVERALLS_TOKEN`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grafov/m3u8/75)

Remove unnecessary args in goveralls

---

reader.go
reader_test.go
structure.go

While HLS Draft in section 3.4.5 require that time should comply with RFC3339, during my work i noticed that many Encoders use ISO8601 where Timezone representation is less strict than RFC3339.
ISO8601 allow to expose TZ in several ways:
```
DateTime/Zone
<time>Z
<time>±hh:mm (by RFC3339)
<time>±hhmm
<time>±hh
```
Example of manifest where we getting Parser error:
```
#EXTM3U
#EXT-X-TARGETDURATION:8
#EXT-X-PROGRAM-DATE-TIME:2017-01-30T17:26:04+0100
#EXT-X-MEDIA-SEQUENCE:855733
#EXTINF:8,
1478947334-fast-1920-1080-2750000-855733.ts
#EXTINF:8,
1478947334-fast-1920-1080-2750000-855734.ts
#EXTINF:8,
1478947334-fast-1920-1080-2750000-855735.ts
```
Error itself:
`parsing time "2017-01-30T17:26:04+0100" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "+0100" as "Z07:00"`
But while RFC3339 …

Time Parsing fix for #EXT-X-PROGRAM-DATE-TIME

---

reader.go
reader_test.go

*This is a potential breaking change*
Previously we would skip a segment which doesn't have a comma in the
For example, the following playlist would have a single nil segment.
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
c_1267327549363093.ts
```
The new behaviour will cause an error to be returned when parsing if
we're operating in strict mode. If we're not operating in strict mode
the duration will be parsed succesfully as 10.000, with an empty title.
Fixes #84.

Make comma optional in #EXTINF when strict mode is false

---

README.md

I've made an webpage that is showing m3u8 format of URL which user inserted. It is built on your parser. If you don't mind, could you add my project to Library Usage section in your README?
Here is the my project link and screenshot.
https://github.com/jeongmin/m3u8-reader

added m3u8-reader project to Library usage section in REAME

---

writer.go

Fix https://github.com/grafov/m3u8/issues/72

seq num slide fix

---

reader_test.go
writer.go
writer_test.go

Add `MediaSegment.SeqId` support.

Feature: Support MediaSegment@SeqId.

---

writer.go

When rendering a mediaplaylist with a DiscontinuitySeq different than 0 a new line is missing, so is being displayed as:
```
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-MEDIA-SEQUENCE:15150186350000
#EXT-X-TARGETDURATION:2
#EXT-X-DISCONTINUITY-SEQUENCE:1#EXTINF:2.000,
```
instead of: 
```
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-MEDIA-SEQUENCE:15150186350000
#EXT-X-TARGETDURATION:2
#EXT-X-DISCONTINUITY-SEQUENCE:1
#EXTINF:2.000,
```

fix: add new line after #EXT-X-DISCONTINUITY-SEQUENCE
